# Build
FROM node:14-alpine AS build

WORKDIR /tmp

RUN apk add \
    python3 \
    python3-dev \
    py-pip \
    build-base \
    bash \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*

COPY package.json yarn.lock ./

RUN yarn --frozen-lockfile

# Runner
FROM node:14-alpine AS runner

WORKDIR /usr/src/app

COPY --from=build /tmp/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD ["yarn", "start:local"]